name: Test Vuln Action
on: [ pull_request ]
jobs:
  test-vuln-action-from-pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        run: |
          cat test.txt
